### ISSUE TITLE
request returns 403

### ISSUE THREAD

**Issue by Radu-Dunarentu** [fuzzmz/WorldclassGymBooking#1]
> Traceback (most recent call last):
  File "C:\Users\Radu\Desktop\wc_reservation.py", line 62, in <module>
    main()
  File "C:\Users\Radu\Desktop\wc_reservation.py", line 56, in main
    cookie = login(memberemail, memberpin)
  File "C:\Users\Radu\Desktop\wc_reservation.py", line 13, in login
    page = urllib2.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

I get this error even with the following header

` headers = {
        'Cookie': cookies, 
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}`

**Comment by fuzzmz** [comment]
I'll take a look at this. Most likely something changed between the time when I wrote this script and now.
